;; Reformats preceding sexp to potentially span multiple lines; then indents it properly.
;; From tali713 on FreeNode #emacs.
(defun format-reindent-defun ()
  (interactive)
  (let ((beg (progn (beginning-of-defun)
		    (point-marker)))
	(end (progn (end-of-defun)
		    (point-marker))))
    (goto-char beg)
    (while (and (< (point)
		   end)
		(search-forward ")"))
      (when (and (not (eq (get-text-property (point)
					     'face)
			  'font-lock-string-face))
		 (not (delete-horizontal-space))
		 (looking-at (rx (not (any ")\n")))))
	(insert "\n")))
    (indent-region beg end)
    (goto-char end)))
